from enum import Enum,IntEnum
class RiceRoundErrorDef(IntEnum):
	SUCCESS=0;HTTP_OK=200;HTTP_UNAUTHORIZED=401;HTTP_INTERNAL_ERROR=500;HTTP_SERVICE_UNAVAILABLE=503;HTTP_TIMEOUT=408;NETWORK_ERROR=1;REQUEST_ERROR=2;NO_TOKEN_ERROR=3;UNKNOWN_ERROR=600;OVER_MAX_ERROR=998;ERROR_EXECUTABLE_NOT_FOUND=1001;ERROR_START_EXCEPTION=1002;ERROR_PROCESS_EXIT=1003;ERROR_RESTART_EXCEPTION=1004;ERROR_MACHINE_CODE_BASE=1000;ERROR_SECRET_TOKEN_BASE=1100;ERROR_SECRET_TOKEN=1101;ERROR_INSTALL_CLIENT_TOML=1102
	@staticmethod
	def calc_error_code(base_value,error_code):
		B=error_code;A=base_value;C=1000
		if B<C:
			if B!=0:return A+B
			else:return A+RiceRoundErrorDef.UNKNOWN_ERROR
		else:return A+RiceRoundErrorDef.OVER_MAX_ERROR